            - name: build-htms
  # You may pin to the exact commit or the version.
  # uses: tnichols217/htms@a4b03588edd0e44ccf79a6f53feeabe6b9acef44
  uses: tnichols217/htms@a2
  with:
    # Source directory to build
    input: # optional, default is ./src
    # Output directory of build
    output: # optional, default is ./out
    # Config file to use
    config: # optional, default is none
    # Branch, commit hash, or tag of htms to use
    branch: # optional, default is 
          
